# Generated by Django 5.0.3 on 2024-04-17 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Event',
            new_name='Discipline',
        ),
        migrations.AlterModelOptions(
            name='record',
            options={'ordering': ['performance', '-record_date']},
        ),
        migrations.RenameField(
            model_name='record',
            old_name='event',
            new_name='discipline',
        ),
        migrations.AlterUniqueTogether(
            name='record',
            unique_together={('holder', 'discipline', 'performance')},
        ),
    ]
