# Generated by Django 5.0.3 on 2024-04-18 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_rename_event_discipline_alter_record_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Place',
            new_name='Venue',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='place',
            new_name='venue',
        ),
    ]
