# Generated by Django 5.0.3 on 2024-04-22 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_rename_place_venue_rename_place_record_venue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='performance',
            field=models.FloatField(null=True),
        ),
    ]
