# Generated by Django 5.0.3 on 2024-05-23 11:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0006_goal_current_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='wind',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(-9.9), django.core.validators.MaxValueValidator(9.9)]),
        ),
    ]
