# Generated by Django 5.0.3 on 2024-05-23 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0007_record_wind'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='ranking',
            field=models.IntegerField(null=True),
        ),
    ]
