# Generated by Django 5.0.3 on 2024-05-28 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0010_record_progression'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='record',
            options={},
        ),
        migrations.AddField(
            model_name='stadium',
            name='indoors_outdoors',
            field=models.CharField(choices=[('indoors', 'Indoors'), ('outdoors', 'Outdoors')], default='outdoors', max_length=8),
        ),
        migrations.AlterField(
            model_name='goal',
            name='venue',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='records.venue'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='stadium_name',
            field=models.CharField(max_length=30),
        ),
    ]
