# Generated by Django 5.0.3 on 2024-05-28 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0011_alter_record_options_stadium_indoors_outdoors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agegroup',
            name='age_group',
            field=models.CharField(choices=[('men', 'Men'), ('women', 'Women'), ('menU20', 'MenU20'), ('womenU20', 'WomenU20')], default='men', max_length=8),
        ),
        migrations.AlterField(
            model_name='goal',
            name='current_record',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
