# Generated by Django 5.0.3 on 2024-05-28 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0012_alter_agegroup_age_group_alter_goal_current_record'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agegroup',
            name='age_group',
        ),
        migrations.AddField(
            model_name='agegroup',
            name='age_groups',
            field=models.CharField(choices=[('men', 'Men'), ('women', 'Women'), ('menU20', 'MenU20'), ('womenU20', 'WomenU20')], default='men', max_length=8),
        ),
    ]
