# Generated by Django 5.0.3 on 2024-05-28 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0013_remove_agegroup_age_group_agegroup_age_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agegroup',
            name='age_groups',
        ),
        migrations.AddField(
            model_name='agegroup',
            name='age_group',
            field=models.CharField(default='Men', max_length=10),
            preserve_default=False,
        ),
    ]
