# Generated by Django 5.0.6 on 2024-06-04 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0015_agegroup_age_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agegroup',
            name='age_groups',
        ),
    ]
