# Generated by Django 5.0.6 on 2024-06-04 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0016_remove_agegroup_age_groups'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='record',
            unique_together={('holder', 'discipline', 'performance', 'age_group')},
        ),
    ]
